version: '3.9'

services:
  database:
    image: 'postgres:13'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=podcast
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
    driver: local