// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routes

import (
	"github.com/google/wire"
	"podcast/controllers"
	"podcast/database"
	"podcast/gateway"
	"podcast/repositories"
	"podcast/services"
)

// Injectors from wire.go:

func CreateAuthController() *controllers.AuthController {
	db := database.Connection()
	usersRepository := repositories.NewUsersRepository(db)
	smtpMailer := gateway.NewSMTPMailer()
	emailService := services.NewEmailService(smtpMailer)
	authService := services.NewAuthService(usersRepository, emailService)
	authController := controllers.NewAuthController(authService)
	return authController
}

func CreatePodcastsController() *controllers.PodcastsController {
	db := database.Connection()
	podcastsRepository := repositories.NewPodcastsRepository(db)
	usersRepository := repositories.NewUsersRepository(db)
	subscriptionsRepository := repositories.NewSubscriptionsRepository(db)
	usersService := services.NewUsersService(usersRepository, subscriptionsRepository)
	stripeGateway := gateway.NewStripeGateway()
	stripeService := services.NewStripeService(stripeGateway, subscriptionsRepository)
	podcastsService := services.NewPodcastsService(podcastsRepository, usersService, stripeService)
	podcastsController := controllers.NewPodcastsController(podcastsService)
	return podcastsController
}

func CreateEpisodesController() *controllers.EpisodesController {
	db := database.Connection()
	episodesRepository := repositories.NewEpisodesRepository(db)
	podcastsRepository := repositories.NewPodcastsRepository(db)
	usersRepository := repositories.NewUsersRepository(db)
	subscriptionsRepository := repositories.NewSubscriptionsRepository(db)
	usersService := services.NewUsersService(usersRepository, subscriptionsRepository)
	stripeGateway := gateway.NewStripeGateway()
	stripeService := services.NewStripeService(stripeGateway, subscriptionsRepository)
	podcastsService := services.NewPodcastsService(podcastsRepository, usersService, stripeService)
	episodesService := services.NewEpisodesService(episodesRepository, podcastsService)
	episodesController := controllers.NewEpisodesController(episodesService)
	return episodesController
}

func CreateWebhooksController() *controllers.WebhooksController {
	stripeGateway := gateway.NewStripeGateway()
	db := database.Connection()
	subscriptionsRepository := repositories.NewSubscriptionsRepository(db)
	stripeService := services.NewStripeService(stripeGateway, subscriptionsRepository)
	webhooksController := controllers.NewWebhooksController(stripeService)
	return webhooksController
}

// wire.go:

var podcastUserStripeSet = wire.NewSet(services.NewPodcastsService, services.NewUsersService, services.NewStripeService, gateway.NewStripeGateway, repositories.NewUsersRepository, repositories.NewPodcastsRepository, repositories.NewSubscriptionsRepository)
