// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"podcast/database"
	"podcast/gateways/mailing"
	"podcast/repositories"
)

// Injectors from wire.go:

func CreateAuthService() *AuthService {
	db := database.Connection()
	usersRepository := repositories.NewUsersRepository(db)
	smtpMailer := mailing.NewSMTPMailer()
	emailService := NewEmailService(smtpMailer)
	authService := NewAuthService(usersRepository, emailService)
	return authService
}
