// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"podcast/database"
	"podcast/gateways/mailing"
	"podcast/repositories"
	"podcast/services"
)

// Injectors from wire.go:

func CreateAuthService() *services.AuthService {
	db := database.Connection()
	usersRepository := repositories.NewUsersRepository(db)
	smtpMailer := mailing.NewSMTPMailer()
	emailService := services.NewEmailService(smtpMailer)
	authService := services.NewAuthService(usersRepository, emailService)
	return authService
}
